### ISSUE TITLE
runtime error during pretrain of SSL model

### ISSUE THREAD

**Issue by sorenmacbeth** [manujosephv/pytorch_tabular#304]
I'm hitting this error when trying to `pretrain` my SSL model. Any tips at places to start looking would be appreciated!

```python
Traceback (most recent call last):
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/bin/nl_segmenter", line 8, in <module>
    sys.exit(train())
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/nl_segmenter/trainer.py", line 313, in train
    dae = train_model(
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/nl_segmenter/nn.py", line 137, in train_model
    tabular_model.pretrain(train=train, validation=val)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_tabular/tabular_model.py", line 764, in pretrain
    return self.train(model, datamodule, callbacks, max_epochs, min_epochs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_tabular/tabular_model.py", line 583, in train
    self.trainer.fit(self.model, train_loader, val_loader)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_tabular/ssl_models/base_model.py", line 156, in validation_step
    self.calculate_loss(output, tag="valid")
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/pytorch_tabular/ssl_models/dae/dae.py", line 194, in calculate_loss
    loss = self.losses[type_](out.reconstructed, out.original) * getattr(self.loss_weights, type_)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 720, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/Users/soren/mambaforge/envs/nl-pytorch-tabular/lib/python3.10/site-packages/torch/nn/functional.py", line 3162, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: result type Float can't be cast to the desired output type Long
```

**Comment by manujosephv** [comment]
Looks like your categorical column data type is float?`binary_cross_entropy` requires `Long`, which means `int64` in pandas. Can you check if that is the issue?

**Comment by sorenmacbeth** [comment]
all of my categorical columns are int64 in the train and validation set

**Comment by sorenmacbeth** [comment]
@manujosephv ok, I've found errors that can happen with categorical cols in the SSL model. If a categorical column has a value that is present in the training set, but not present in the validation set, odd behaviour/errors occur. the `setup` method in the tabular_datamodule calls `preprocess_data` first on the training set with stage `fit` and then on the validation set with stage `inference`. if the validation set has a value that wasn't present in the training set, the fitted encoder doesn't know how to encode the value and by default it encodes it as NaN and a random side effect that column also is left as float32 type for the rest of values.

No actual error is thrown until `train` is called and `self.datamodule.val_dataloader()` is called. then a `pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer` is thrown.

**Comment by sorenmacbeth** [comment]
ok, I've made a small code example that throws the same error. here is a print output of

**Comment by manujosephv** [comment]
I haven't had time to look at the original problem yet, but in this example, the problem is that ` F.binary_cross_entropy_with_logits` expects the input and target to be float. 

I know earlier I said `binary_cross_entropy_with_logits` needs Long. I take it back! I wrote it in between a vacation on the beach ;) 

```python
loss = F.binary_cross_entropy_with_logits(input.float(), target.float())
```
This should work

But the original problem may be something else. I'll take a look at that very soon.

**Comment by sorenmacbeth** [comment]
@manujosephv right, but this part: 
```python
binary: output_tuple(original=tensor([[1],
        [1],
        [1],
        ...,
        [1],
        [1],
        [1]]), reconstructed=tensor([[0.6716],
        [0.3465],
        [0.5530],
        ...,
        [0.2264],
        [0.1202],
        [0.1020]]))
```

was from a pretrain of my actual data and the tensor is int64 for binary features and it should be float64, i think. That might be the source of the bug

**Comment by manujosephv** [comment]
I agree... can you help in writing a reproducible and self-contained example so that I can start debugging at my end?

**Comment by sorenmacbeth** [comment]
yes, ill try.

**Comment by sorenmacbeth** [comment]
@manujosephv ok, phew! after much nashing of teeth and many print statements, I have finally figured out how to reliably reproduce the error. All you need is a dataset with a categorical column where all the values are identical. that is `df["cat1"].nunique() == 1`

**Comment by manujosephv** [comment]
I'll take a look at this
