### ISSUE TITLE
cross_validate error when running with 0 categorical_cols []

### ISSUE THREAD

**Issue by furyhawk** [manujosephv/pytorch_tabular#406]
**Describe the bug**
cross_validate() produce error when running with 0 categorical_cols [] **&** reset_datamodule=False.
```
ValueError: y contains previously unseen labels: 0
```
Any other change in the above parameters run cross_validate() successfully.

**To Reproduce**

create a dataset with 0 n_categories feature:
```
data, cat_col_names, num_col_names = make_mixed_dataset(
    task="classification", n_samples=1000, n_features=20, n_categories=0, n_targets=2
)
```

run cross_validation() with reset_datamodule=False:
```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    cv_scores, oof_predictions = tabular_model.cross_validate(
        cv=5, train=train, metric=None, return_oof=False, reset_datamodule=False
    )
```

error:
```
2024-02-24 16:01:37,001 - {pytorch_tabular.tabular_model:1958} - INFO - Running Fold 1/5
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-02-24 16:01:39,650 - {pytorch_tabular.tabular_model:1985} - INFO - Fold 1/5 score: 0.8799999952316284
2024-02-24 16:01:39,653 - {pytorch_tabular.tabular_model:1958} - INFO - Running Fold 2/5
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/utils/_encode.py", line 225, in _encode
    return _map_to_integer(values, uniques)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/utils/_encode.py", line 165, in _map_to_integer
    return np.array([table[v] for v in values])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/utils/_encode.py", line 165, in <listcomp>
    return np.array([table[v] for v in values])
                     ~~~~~^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/utils/_encode.py", line 159, in __missing__
    raise KeyError(key)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/furyhawk/projects/cudo_ai/test.py", line 80, in <module>
    cv_scores, oof_predictions = tabular_model.cross_validate(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_model.py", line 1982, in cross_validate
    result = self.evaluate(val_fold, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_model.py", line 1180, in evaluate
    test_loader = self.datamodule.prepare_inference_dataloader(test)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_datamodule.py", line 826, in prepare_inference_dataloader
    df = self._prepare_inference_data(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_datamodule.py", line 809, in _prepare_inference_data
    df, _ = self.preprocess_data(df, stage="inference")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_datamodule.py", line 441, in preprocess_data
    data = self._label_encode_target(data, stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/pytorch_tabular/tabular_datamodule.py", line 383, in _label_encode_target
    data[self.config.target[0]] = self.label_encoder.transform(data[self.config.target[0]])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/preprocessing/_label.py", line 137, in transform
    return _encode(y, uniques=self.classes_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/furyhawk/Library/Caches/pypoetry/virtualenvs/cudo-ai-NgEsjsKn-py3.11/lib/python3.11/site-packages/sklearn/utils/_encode.py", line 227, in _encode
    raise ValueError(f"y contains previously unseen labels: {str(e)}")
ValueError: y contains previously unseen labels: 0
```

**Expected behavior**
cross_validation successfully =)

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 14.3.1 (23D60)

**Additional context**
```
pytorch-lightning         2.1.4
pytorch-tabnet            4.1.0
pytorch-tabular           1.1.0
scikit-learn              1.4.1.post1
torch                     2.2.1
```

**Comment by manujosephv** [comment]
Thanks for this issue.. this does seem to be a problem with the categorical encoder I'm using.. Will take a look at this soon

**Comment by manujosephv** [comment]
No, I was wrong! The issue is with the way dataframes are handled (without making copies)  #414 Fixes this
