### ISSUE TITLE
Cannot create or construct a <class 'pstats.Stats'> object from <cProfile.Profile object at 0x7f56f5f9ddc0

### ISSUE THREAD

**Issue by bogus215** [manujosephv/pytorch_tabular#83]
When I run such as, model.evaulate(test)...

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_tabular/tabular_model.py", line 557, in evaluate
    result = self.trainer.test(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in test
    results = self._run(model)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 793, in dispatch
    self.accelerator.start_evaluating(self)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 99, in start_evaluating
    self.training_type_plugin.start_evaluating(trainer)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 148, in start_evaluating
    self._results = trainer.run_stage()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 804, in run_stage
    return self.run_evaluate()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in run_evaluate
    eval_loop_results = self.run_evaluation()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1006, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 106, in on_evaluation_end
    self.trainer.profiler.describe()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 151, in describe
    summary = self.summary()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 372, in summary
    ps = pstats.Stats(pr, stream=s).strip_dirs().sort_stats('cumulative')
  File "/opt/conda/envs/rapids/lib/python3.8/pstats.py", line 96, in __init__
    self.init(arg)
  File "/opt/conda/envs/rapids/lib/python3.8/pstats.py", line 110, in init
    self.load_stats(arg)
  File "/opt/conda/envs/rapids/lib/python3.8/pstats.py", line 136, in load_stats
    raise TypeError("Cannot create or construct a %r object from %r"
TypeError: Cannot create or construct a <class 'pstats.Stats'> object from <cProfile.Profile object at 0x7f56f5f9ddc0>

**Comment by manujosephv** [comment]
Looks like a PyTorch Lightning bug. Are you running with a profiler?

**Comment by bogus215** [comment]
@manujosephv , Yes it is.

**Comment by manujosephv** [comment]
I think you should raise a bug, along with a reproducible example, to PyTorch Lightning... meanwhile, probably disable the profiler and try running it.
